/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ncwcandroid.ui;

public final class R {
    public static final class anim {
        public static final int anim_enter=0x7f040000;
        public static final int anim_exit=0x7f040001;
        public static final int back_enter=0x7f040002;
        public static final int back_exit=0x7f040003;
        public static final int push_bottom_in=0x7f040004;
        public static final int push_bottom_in2=0x7f040005;
        public static final int push_bottom_out=0x7f040006;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int max=0x7f010005;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundColor=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundProgressColor=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundWidth=0x7f010002;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>STROKE</code></td><td>0</td><td></td></tr>
<tr><td><code>FILL</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int style=0x7f010007;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f010003;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textIsDisplayable=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSize=0x7f010004;
    }
    public static final class color {
        public static final int Background=0x7f07001d;
        public static final int ButtonBG=0x7f070020;
        public static final int ImageBG=0x7f070021;
        public static final int Red=0x7f07000e;
        public static final int TextColor=0x7f07001f;
        public static final int abc_search_url_text_normal=0x7f070006;
        public static final int abc_search_url_text_pressed=0x7f07000c;
        public static final int abc_search_url_text_selected=0x7f07000b;
        public static final int actioncolor=0x7f070005;
        public static final int actionsnl=0x7f070008;
        public static final int arc_progress_background=0x7f07002b;
        public static final int arc_progress_sweeping_color=0x7f07002c;
        /**  主背景色 
         */
        public static final int bg_color=0x7f070000;
        public static final int bggray=0x7f070016;
        /**  顶部状态栏颜色 
         */
        public static final int bgtitlecolor=0x7f070001;
        public static final int black=0x7f07001c;
        public static final int blue=0x7f070048;
        public static final int btn_class=0x7f07003c;
        public static final int btn_class_color=0x7f07003b;
        public static final int btn_class_txt=0x7f07003d;
        public static final int btn_compile_bg=0x7f070040;
        public static final int btn_menu_txt_co=0x7f070043;
        public static final int btn_menu_txt_color=0x7f070044;
        public static final int btn_shouye_bg=0x7f07003f;
        public static final int btn_teacher_bg=0x7f070041;
        public static final int btn_title_bg=0x7f070042;
        public static final int btnsharp=0x7f070009;
        public static final int darkgray=0x7f070017;
        public static final int default_window_bg=0x7f070036;
        public static final int default_window_bg_night=0x7f070037;
        public static final int dialog_white_bg=0x7f070047;
        public static final int dimgray=0x7f07001a;
        public static final int dot_bg=0x7f070027;
        public static final int dot_select_color=0x7f070029;
        public static final int dot_unselect_color=0x7f070028;
        public static final int gallery_alpha=0x7f070011;
        public static final int gallery_background=0x7f070010;
        /**  灰色 
         */
        public static final int gg=0x7f07004a;
        public static final int gray=0x7f070015;
        public static final int green=0x7f070049;
        public static final int grentxt=0x7f070004;
        public static final int guide_view_bg=0x7f070032;
        public static final int introtextcolor=0x7f070007;
        public static final int lighter_gray=0x7f070014;
        public static final int lightgray=0x7f070018;
        /**  登录按钮 颜色 
         */
        public static final int login_btn=0x7f070002;
        public static final int login_btned=0x7f070003;
        public static final int logo_text_color=0x7f070046;
        public static final int menu_item_text_highlight=0x7f070039;
        public static final int menu_item_text_normal=0x7f070038;
        public static final int my_setextcolor=0x7f07000a;
        public static final int orange=0x7f07000d;
        public static final int page_back=0x7f070045;
        public static final int popup_window_pressed_bg=0x7f070033;
        public static final int progressbar_app=0x7f07002a;
        public static final int pull_to_refresh_label_color=0x7f070026;
        public static final int sandybrown=0x7f070019;
        public static final int silver=0x7f07001b;
        public static final int simple_333333=0x7f070022;
        public static final int simple_cccccc=0x7f070025;
        public static final int simple_eeeeee=0x7f070024;
        public static final int sparackground=0x7f07001e;
        public static final int tabDark=0x7f070030;
        public static final int tabMedium=0x7f07002f;
        public static final int tabTransparent=0x7f070031;
        public static final int tab_text_highlight=0x7f07002e;
        public static final int tab_text_normal=0x7f07002d;
        public static final int tab_txtcolor=0x7f07004b;
        public static final int teacher_subscribe_color=0x7f07003e;
        public static final int title_bg_color=0x7f07003a;
        public static final int title_text_color=0x7f070034;
        public static final int title_text_color_night=0x7f070035;
        public static final int transparent=0x7f070023;
        public static final int transparent_helf=0x7f07000f;
        public static final int white=0x7f070012;
        public static final int white89=0x7f070013;
    }
    public static final class dimen {
        public static final int DIMEN_100PX=0x7f080070;
        public static final int DIMEN_101PX=0x7f080071;
        public static final int DIMEN_102PX=0x7f080072;
        public static final int DIMEN_103PX=0x7f080073;
        public static final int DIMEN_104PX=0x7f080074;
        public static final int DIMEN_105PX=0x7f080075;
        public static final int DIMEN_106PX=0x7f080076;
        public static final int DIMEN_107PX=0x7f080077;
        public static final int DIMEN_108PX=0x7f080078;
        public static final int DIMEN_109PX=0x7f080079;
        public static final int DIMEN_10PX=0x7f080016;
        public static final int DIMEN_110PX=0x7f08007a;
        public static final int DIMEN_111PX=0x7f08007b;
        public static final int DIMEN_112PX=0x7f08007c;
        public static final int DIMEN_113PX=0x7f08007d;
        public static final int DIMEN_114PX=0x7f08007e;
        public static final int DIMEN_115PX=0x7f08007f;
        public static final int DIMEN_116PX=0x7f080080;
        public static final int DIMEN_117PX=0x7f080081;
        public static final int DIMEN_118PX=0x7f080082;
        public static final int DIMEN_119PX=0x7f080083;
        public static final int DIMEN_11PX=0x7f080017;
        public static final int DIMEN_120PX=0x7f080084;
        public static final int DIMEN_121PX=0x7f080085;
        public static final int DIMEN_122PX=0x7f080086;
        public static final int DIMEN_123PX=0x7f080087;
        public static final int DIMEN_124PX=0x7f080088;
        public static final int DIMEN_125PX=0x7f080089;
        public static final int DIMEN_126PX=0x7f08008a;
        public static final int DIMEN_127PX=0x7f08008b;
        public static final int DIMEN_128PX=0x7f08008c;
        public static final int DIMEN_129PX=0x7f08008d;
        public static final int DIMEN_12PX=0x7f080018;
        public static final int DIMEN_130PX=0x7f08008e;
        public static final int DIMEN_131PX=0x7f08008f;
        public static final int DIMEN_132PX=0x7f080090;
        public static final int DIMEN_133PX=0x7f080091;
        public static final int DIMEN_134PX=0x7f080092;
        public static final int DIMEN_135PX=0x7f080093;
        public static final int DIMEN_136PX=0x7f080094;
        public static final int DIMEN_137PX=0x7f080095;
        public static final int DIMEN_138PX=0x7f080096;
        public static final int DIMEN_139PX=0x7f080097;
        public static final int DIMEN_13PX=0x7f080019;
        public static final int DIMEN_140PX=0x7f080098;
        public static final int DIMEN_141PX=0x7f080099;
        public static final int DIMEN_142PX=0x7f08009a;
        public static final int DIMEN_143PX=0x7f08009b;
        public static final int DIMEN_144PX=0x7f08009c;
        public static final int DIMEN_145PX=0x7f08009d;
        public static final int DIMEN_146PX=0x7f08009e;
        public static final int DIMEN_147PX=0x7f08009f;
        public static final int DIMEN_148PX=0x7f0800a0;
        public static final int DIMEN_149PX=0x7f0800a1;
        public static final int DIMEN_14PX=0x7f08001a;
        public static final int DIMEN_150PX=0x7f0800a2;
        public static final int DIMEN_151PX=0x7f0800a3;
        public static final int DIMEN_152PX=0x7f0800a4;
        public static final int DIMEN_153PX=0x7f0800a5;
        public static final int DIMEN_154PX=0x7f0800a6;
        public static final int DIMEN_155PX=0x7f0800a7;
        public static final int DIMEN_156PX=0x7f0800a8;
        public static final int DIMEN_157PX=0x7f0800a9;
        public static final int DIMEN_158PX=0x7f0800aa;
        public static final int DIMEN_159PX=0x7f0800ab;
        public static final int DIMEN_15PX=0x7f08001b;
        public static final int DIMEN_160PX=0x7f0800ac;
        public static final int DIMEN_161PX=0x7f0800ad;
        public static final int DIMEN_162PX=0x7f0800ae;
        public static final int DIMEN_163PX=0x7f0800af;
        public static final int DIMEN_164PX=0x7f0800b0;
        public static final int DIMEN_165PX=0x7f0800b1;
        public static final int DIMEN_166PX=0x7f0800b2;
        public static final int DIMEN_167PX=0x7f0800b3;
        public static final int DIMEN_168PX=0x7f0800b4;
        public static final int DIMEN_169PX=0x7f0800b5;
        public static final int DIMEN_16PX=0x7f08001c;
        public static final int DIMEN_170PX=0x7f0800b6;
        public static final int DIMEN_171PX=0x7f0800b7;
        public static final int DIMEN_172PX=0x7f0800b8;
        public static final int DIMEN_173PX=0x7f0800b9;
        public static final int DIMEN_174PX=0x7f0800ba;
        public static final int DIMEN_175PX=0x7f0800bb;
        public static final int DIMEN_176PX=0x7f0800bc;
        public static final int DIMEN_177PX=0x7f0800bd;
        public static final int DIMEN_178PX=0x7f0800be;
        public static final int DIMEN_179PX=0x7f0800bf;
        public static final int DIMEN_17PX=0x7f08001d;
        public static final int DIMEN_180PX=0x7f0800c0;
        public static final int DIMEN_181PX=0x7f0800c1;
        public static final int DIMEN_182PX=0x7f0800c2;
        public static final int DIMEN_183PX=0x7f0800c3;
        public static final int DIMEN_184PX=0x7f0800c4;
        public static final int DIMEN_185PX=0x7f0800c5;
        public static final int DIMEN_186PX=0x7f0800c6;
        public static final int DIMEN_187PX=0x7f0800c7;
        public static final int DIMEN_188PX=0x7f0800c8;
        public static final int DIMEN_189PX=0x7f0800c9;
        public static final int DIMEN_18PX=0x7f08001e;
        public static final int DIMEN_190PX=0x7f0800ca;
        public static final int DIMEN_191PX=0x7f0800cb;
        public static final int DIMEN_192PX=0x7f0800cc;
        public static final int DIMEN_193PX=0x7f0800cd;
        public static final int DIMEN_194PX=0x7f0800ce;
        public static final int DIMEN_195PX=0x7f0800cf;
        public static final int DIMEN_196PX=0x7f0800d0;
        public static final int DIMEN_197PX=0x7f0800d1;
        public static final int DIMEN_198PX=0x7f0800d2;
        public static final int DIMEN_199PX=0x7f0800d3;
        public static final int DIMEN_19PX=0x7f08001f;
        public static final int DIMEN_1PX=0x7f08000d;
        public static final int DIMEN_200PX=0x7f0800d4;
        public static final int DIMEN_201PX=0x7f0800d5;
        public static final int DIMEN_202PX=0x7f0800d6;
        public static final int DIMEN_203PX=0x7f0800d7;
        public static final int DIMEN_204PX=0x7f0800d8;
        public static final int DIMEN_205PX=0x7f0800d9;
        public static final int DIMEN_206PX=0x7f0800da;
        public static final int DIMEN_207PX=0x7f0800db;
        public static final int DIMEN_208PX=0x7f0800dc;
        public static final int DIMEN_209PX=0x7f0800dd;
        public static final int DIMEN_20PX=0x7f080020;
        public static final int DIMEN_210PX=0x7f0800de;
        public static final int DIMEN_211PX=0x7f0800df;
        public static final int DIMEN_212PX=0x7f0800e0;
        public static final int DIMEN_213PX=0x7f0800e1;
        public static final int DIMEN_214PX=0x7f0800e2;
        public static final int DIMEN_215PX=0x7f0800e3;
        public static final int DIMEN_216PX=0x7f0800e4;
        public static final int DIMEN_217PX=0x7f0800e5;
        public static final int DIMEN_218PX=0x7f0800e6;
        public static final int DIMEN_219PX=0x7f0800e7;
        public static final int DIMEN_21PX=0x7f080021;
        public static final int DIMEN_220PX=0x7f0800e8;
        public static final int DIMEN_221PX=0x7f0800e9;
        public static final int DIMEN_222PX=0x7f0800ea;
        public static final int DIMEN_223PX=0x7f0800eb;
        public static final int DIMEN_224PX=0x7f0800ec;
        public static final int DIMEN_225PX=0x7f0800ed;
        public static final int DIMEN_226PX=0x7f0800ee;
        public static final int DIMEN_227PX=0x7f0800ef;
        public static final int DIMEN_228PX=0x7f0800f0;
        public static final int DIMEN_229PX=0x7f0800f1;
        public static final int DIMEN_22PX=0x7f080022;
        public static final int DIMEN_230PX=0x7f0800f2;
        public static final int DIMEN_231PX=0x7f0800f3;
        public static final int DIMEN_232PX=0x7f0800f4;
        public static final int DIMEN_233PX=0x7f0800f5;
        public static final int DIMEN_234PX=0x7f0800f6;
        public static final int DIMEN_235PX=0x7f0800f7;
        public static final int DIMEN_236PX=0x7f0800f8;
        public static final int DIMEN_237PX=0x7f0800f9;
        public static final int DIMEN_238PX=0x7f0800fa;
        public static final int DIMEN_239PX=0x7f0800fb;
        public static final int DIMEN_23PX=0x7f080023;
        public static final int DIMEN_240PX=0x7f0800fc;
        public static final int DIMEN_241PX=0x7f0800fd;
        public static final int DIMEN_242PX=0x7f0800fe;
        public static final int DIMEN_243PX=0x7f0800ff;
        public static final int DIMEN_244PX=0x7f080100;
        public static final int DIMEN_245PX=0x7f080101;
        public static final int DIMEN_246PX=0x7f080102;
        public static final int DIMEN_247PX=0x7f080103;
        public static final int DIMEN_248PX=0x7f080104;
        public static final int DIMEN_249PX=0x7f080105;
        public static final int DIMEN_24PX=0x7f080024;
        public static final int DIMEN_250PX=0x7f080106;
        public static final int DIMEN_251PX=0x7f080107;
        public static final int DIMEN_252PX=0x7f080108;
        public static final int DIMEN_253PX=0x7f080109;
        public static final int DIMEN_254PX=0x7f08010a;
        public static final int DIMEN_255PX=0x7f08010b;
        public static final int DIMEN_256PX=0x7f08010c;
        public static final int DIMEN_257PX=0x7f08010d;
        public static final int DIMEN_258PX=0x7f08010e;
        public static final int DIMEN_259PX=0x7f08010f;
        public static final int DIMEN_25PX=0x7f080025;
        public static final int DIMEN_260PX=0x7f080110;
        public static final int DIMEN_261PX=0x7f080111;
        public static final int DIMEN_262PX=0x7f080112;
        public static final int DIMEN_263PX=0x7f080113;
        public static final int DIMEN_264PX=0x7f080114;
        public static final int DIMEN_265PX=0x7f080115;
        public static final int DIMEN_266PX=0x7f080116;
        public static final int DIMEN_267PX=0x7f080117;
        public static final int DIMEN_268PX=0x7f080118;
        public static final int DIMEN_269PX=0x7f080119;
        public static final int DIMEN_26PX=0x7f080026;
        public static final int DIMEN_270PX=0x7f08011a;
        public static final int DIMEN_271PX=0x7f08011b;
        public static final int DIMEN_272PX=0x7f08011c;
        public static final int DIMEN_273PX=0x7f08011d;
        public static final int DIMEN_274PX=0x7f08011e;
        public static final int DIMEN_275PX=0x7f08011f;
        public static final int DIMEN_276PX=0x7f080120;
        public static final int DIMEN_277PX=0x7f080121;
        public static final int DIMEN_278PX=0x7f080122;
        public static final int DIMEN_279PX=0x7f080123;
        public static final int DIMEN_27PX=0x7f080027;
        public static final int DIMEN_280PX=0x7f080124;
        public static final int DIMEN_281PX=0x7f080125;
        public static final int DIMEN_282PX=0x7f080126;
        public static final int DIMEN_283PX=0x7f080127;
        public static final int DIMEN_284PX=0x7f080128;
        public static final int DIMEN_285PX=0x7f080129;
        public static final int DIMEN_286PX=0x7f08012a;
        public static final int DIMEN_287PX=0x7f08012b;
        public static final int DIMEN_288PX=0x7f08012c;
        public static final int DIMEN_289PX=0x7f08012d;
        public static final int DIMEN_28PX=0x7f080028;
        public static final int DIMEN_290PX=0x7f08012e;
        public static final int DIMEN_291PX=0x7f08012f;
        public static final int DIMEN_292PX=0x7f080130;
        public static final int DIMEN_293PX=0x7f080131;
        public static final int DIMEN_294PX=0x7f080132;
        public static final int DIMEN_295PX=0x7f080133;
        public static final int DIMEN_296PX=0x7f080134;
        public static final int DIMEN_297PX=0x7f080135;
        public static final int DIMEN_298PX=0x7f080136;
        public static final int DIMEN_299PX=0x7f080137;
        public static final int DIMEN_29PX=0x7f080029;
        public static final int DIMEN_2PX=0x7f08000e;
        public static final int DIMEN_300PX=0x7f080138;
        public static final int DIMEN_301PX=0x7f080139;
        public static final int DIMEN_302PX=0x7f08013a;
        public static final int DIMEN_303PX=0x7f08013b;
        public static final int DIMEN_304PX=0x7f08013c;
        public static final int DIMEN_305PX=0x7f08013d;
        public static final int DIMEN_306PX=0x7f08013e;
        public static final int DIMEN_307PX=0x7f08013f;
        public static final int DIMEN_308PX=0x7f080140;
        public static final int DIMEN_309PX=0x7f080141;
        public static final int DIMEN_30PX=0x7f08002a;
        public static final int DIMEN_310PX=0x7f080142;
        public static final int DIMEN_311PX=0x7f080143;
        public static final int DIMEN_312PX=0x7f080144;
        public static final int DIMEN_313PX=0x7f080145;
        public static final int DIMEN_314PX=0x7f080146;
        public static final int DIMEN_315PX=0x7f080147;
        public static final int DIMEN_316PX=0x7f080148;
        public static final int DIMEN_317PX=0x7f080149;
        public static final int DIMEN_318PX=0x7f08014a;
        public static final int DIMEN_319PX=0x7f08014b;
        public static final int DIMEN_31PX=0x7f08002b;
        public static final int DIMEN_320PX=0x7f08014c;
        public static final int DIMEN_321PX=0x7f08014d;
        public static final int DIMEN_322PX=0x7f08014e;
        public static final int DIMEN_323PX=0x7f08014f;
        public static final int DIMEN_324PX=0x7f080150;
        public static final int DIMEN_325PX=0x7f080151;
        public static final int DIMEN_326PX=0x7f080152;
        public static final int DIMEN_327PX=0x7f080153;
        public static final int DIMEN_328PX=0x7f080154;
        public static final int DIMEN_329PX=0x7f080155;
        public static final int DIMEN_32PX=0x7f08002c;
        public static final int DIMEN_330PX=0x7f080156;
        public static final int DIMEN_331PX=0x7f080157;
        public static final int DIMEN_332PX=0x7f080158;
        public static final int DIMEN_333PX=0x7f080159;
        public static final int DIMEN_334PX=0x7f08015a;
        public static final int DIMEN_335PX=0x7f08015b;
        public static final int DIMEN_336PX=0x7f08015c;
        public static final int DIMEN_337PX=0x7f08015d;
        public static final int DIMEN_338PX=0x7f08015e;
        public static final int DIMEN_339PX=0x7f08015f;
        public static final int DIMEN_33PX=0x7f08002d;
        public static final int DIMEN_340PX=0x7f080160;
        public static final int DIMEN_341PX=0x7f080161;
        public static final int DIMEN_342PX=0x7f080162;
        public static final int DIMEN_343PX=0x7f080163;
        public static final int DIMEN_344PX=0x7f080164;
        public static final int DIMEN_345PX=0x7f080165;
        public static final int DIMEN_346PX=0x7f080166;
        public static final int DIMEN_347PX=0x7f080167;
        public static final int DIMEN_348PX=0x7f080168;
        public static final int DIMEN_349PX=0x7f080169;
        public static final int DIMEN_34PX=0x7f08002e;
        public static final int DIMEN_350PX=0x7f08016a;
        public static final int DIMEN_351PX=0x7f08016b;
        public static final int DIMEN_352PX=0x7f08016c;
        public static final int DIMEN_353PX=0x7f08016d;
        public static final int DIMEN_354PX=0x7f08016e;
        public static final int DIMEN_355PX=0x7f08016f;
        public static final int DIMEN_356PX=0x7f080170;
        public static final int DIMEN_357PX=0x7f080171;
        public static final int DIMEN_358PX=0x7f080172;
        public static final int DIMEN_359PX=0x7f080173;
        public static final int DIMEN_35PX=0x7f08002f;
        public static final int DIMEN_360PX=0x7f080174;
        public static final int DIMEN_361PX=0x7f080175;
        public static final int DIMEN_362PX=0x7f080176;
        public static final int DIMEN_363PX=0x7f080177;
        public static final int DIMEN_364PX=0x7f080178;
        public static final int DIMEN_365PX=0x7f080179;
        public static final int DIMEN_366PX=0x7f08017a;
        public static final int DIMEN_367PX=0x7f08017b;
        public static final int DIMEN_368PX=0x7f08017c;
        public static final int DIMEN_369PX=0x7f08017d;
        public static final int DIMEN_36PX=0x7f080030;
        public static final int DIMEN_370PX=0x7f08017e;
        public static final int DIMEN_371PX=0x7f08017f;
        public static final int DIMEN_372PX=0x7f080180;
        public static final int DIMEN_373PX=0x7f080181;
        public static final int DIMEN_374PX=0x7f080182;
        public static final int DIMEN_375PX=0x7f080183;
        public static final int DIMEN_376PX=0x7f080184;
        public static final int DIMEN_377PX=0x7f080185;
        public static final int DIMEN_378PX=0x7f080186;
        public static final int DIMEN_379PX=0x7f080187;
        public static final int DIMEN_37PX=0x7f080031;
        public static final int DIMEN_380PX=0x7f080188;
        public static final int DIMEN_381PX=0x7f080189;
        public static final int DIMEN_382PX=0x7f08018a;
        public static final int DIMEN_383PX=0x7f08018b;
        public static final int DIMEN_384PX=0x7f08018c;
        public static final int DIMEN_385PX=0x7f08018d;
        public static final int DIMEN_386PX=0x7f08018e;
        public static final int DIMEN_387PX=0x7f08018f;
        public static final int DIMEN_388PX=0x7f080190;
        public static final int DIMEN_389PX=0x7f080191;
        public static final int DIMEN_38PX=0x7f080032;
        public static final int DIMEN_390PX=0x7f080192;
        public static final int DIMEN_391PX=0x7f080193;
        public static final int DIMEN_392PX=0x7f080194;
        public static final int DIMEN_393PX=0x7f080195;
        public static final int DIMEN_394PX=0x7f080196;
        public static final int DIMEN_395PX=0x7f080197;
        public static final int DIMEN_396PX=0x7f080198;
        public static final int DIMEN_397PX=0x7f080199;
        public static final int DIMEN_398PX=0x7f08019a;
        public static final int DIMEN_399PX=0x7f08019b;
        public static final int DIMEN_39PX=0x7f080033;
        public static final int DIMEN_3PX=0x7f08000f;
        public static final int DIMEN_400PX=0x7f08019c;
        public static final int DIMEN_40PX=0x7f080034;
        public static final int DIMEN_41PX=0x7f080035;
        public static final int DIMEN_42PX=0x7f080036;
        public static final int DIMEN_43PX=0x7f080037;
        public static final int DIMEN_44PX=0x7f080038;
        public static final int DIMEN_45PX=0x7f080039;
        public static final int DIMEN_46PX=0x7f08003a;
        public static final int DIMEN_47PX=0x7f08003b;
        public static final int DIMEN_48PX=0x7f08003c;
        public static final int DIMEN_49PX=0x7f08003d;
        public static final int DIMEN_4PX=0x7f080010;
        public static final int DIMEN_50PX=0x7f08003e;
        public static final int DIMEN_51PX=0x7f08003f;
        public static final int DIMEN_52PX=0x7f080040;
        public static final int DIMEN_53PX=0x7f080041;
        public static final int DIMEN_54PX=0x7f080042;
        public static final int DIMEN_55PX=0x7f080043;
        public static final int DIMEN_56PX=0x7f080044;
        public static final int DIMEN_57PX=0x7f080045;
        public static final int DIMEN_58PX=0x7f080046;
        public static final int DIMEN_59PX=0x7f080047;
        public static final int DIMEN_5PX=0x7f080011;
        public static final int DIMEN_60PX=0x7f080048;
        public static final int DIMEN_61PX=0x7f080049;
        public static final int DIMEN_62PX=0x7f08004a;
        public static final int DIMEN_63PX=0x7f08004b;
        public static final int DIMEN_64PX=0x7f08004c;
        public static final int DIMEN_65PX=0x7f08004d;
        public static final int DIMEN_66PX=0x7f08004e;
        public static final int DIMEN_67PX=0x7f08004f;
        public static final int DIMEN_68PX=0x7f080050;
        public static final int DIMEN_69PX=0x7f080051;
        public static final int DIMEN_6PX=0x7f080012;
        public static final int DIMEN_70PX=0x7f080052;
        public static final int DIMEN_71PX=0x7f080053;
        public static final int DIMEN_72PX=0x7f080054;
        public static final int DIMEN_73PX=0x7f080055;
        public static final int DIMEN_74PX=0x7f080056;
        public static final int DIMEN_75PX=0x7f080057;
        public static final int DIMEN_76PX=0x7f080058;
        public static final int DIMEN_77PX=0x7f080059;
        public static final int DIMEN_78PX=0x7f08005a;
        public static final int DIMEN_79PX=0x7f08005b;
        public static final int DIMEN_7PX=0x7f080013;
        public static final int DIMEN_80PX=0x7f08005c;
        public static final int DIMEN_81PX=0x7f08005d;
        public static final int DIMEN_82PX=0x7f08005e;
        public static final int DIMEN_83PX=0x7f08005f;
        public static final int DIMEN_84PX=0x7f080060;
        public static final int DIMEN_85PX=0x7f080061;
        public static final int DIMEN_86PX=0x7f080062;
        public static final int DIMEN_87PX=0x7f080063;
        public static final int DIMEN_88PX=0x7f080064;
        public static final int DIMEN_89PX=0x7f080065;
        public static final int DIMEN_8PX=0x7f080014;
        public static final int DIMEN_90PX=0x7f080066;
        public static final int DIMEN_91PX=0x7f080067;
        public static final int DIMEN_92PX=0x7f080068;
        public static final int DIMEN_93PX=0x7f080069;
        public static final int DIMEN_94PX=0x7f08006a;
        public static final int DIMEN_95PX=0x7f08006b;
        public static final int DIMEN_96PX=0x7f08006c;
        public static final int DIMEN_97PX=0x7f08006d;
        public static final int DIMEN_98PX=0x7f08006e;
        public static final int DIMEN_99PX=0x7f08006f;
        public static final int DIMEN_9PX=0x7f080015;
        /** 
         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.

    
         */
        public static final int activity_horizontal_margin=0x7f080004;
        public static final int activity_vertical_margin=0x7f080005;
        public static final int bottom_tab_font_size=0x7f080009;
        public static final int bottom_tab_layout_marginTop=0x7f08000a;
        public static final int bottom_tab_padding_drawable=0x7f080006;
        public static final int bottom_tab_padding_left=0x7f080008;
        public static final int bottom_tab_padding_up=0x7f080007;
        public static final int slidingmenu_offset=0x7f08000c;
        public static final int text24size=0x7f080002;
        public static final int text30size=0x7f080003;
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int text32size=0x7f080000;
        public static final int text36size=0x7f080001;
        public static final int title_text_size=0x7f08000b;
    }
    public static final class drawable {
        public static final int arrow=0x7f020000;
        public static final int back=0x7f020001;
        public static final int backicon=0x7f020002;
        public static final int beijing=0x7f020003;
        public static final int bg_edittext=0x7f020004;
        public static final int bg_edittext_focused=0x7f020005;
        public static final int bg_edittext_normal=0x7f020006;
        public static final int bianji=0x7f020007;
        public static final int bookmark_l=0x7f020008;
        public static final int bookmark_r=0x7f020009;
        public static final int bottomandtopsharp=0x7f02000a;
        public static final int chakanshiyongjieguo=0x7f02000b;
        public static final int chanpin=0x7f02000c;
        public static final int chanpinzhiliang=0x7f02000d;
        public static final int check=0x7f02000e;
        public static final int check_sex=0x7f02000f;
        public static final int checkboxshap=0x7f020010;
        public static final int checkboxshap2=0x7f020011;
        public static final int chenggong=0x7f020012;
        public static final int clock=0x7f020013;
        public static final int commitsharp=0x7f020014;
        public static final int corners_bg=0x7f020015;
        public static final int corners_button_bg=0x7f020016;
        public static final int corners_button_no_bg=0x7f020017;
        public static final int corners_share_bg=0x7f020018;
        public static final int cup=0x7f020019;
        public static final int default_item=0x7f02001a;
        public static final int dengpao=0x7f02001b;
        public static final int disk=0x7f02001c;
        public static final int dot=0x7f02001d;
        public static final int dot_noselected=0x7f02001e;
        public static final int dot_selected=0x7f02001f;
        public static final int fabiao=0x7f020020;
        public static final int fanhui=0x7f020021;
        public static final int files=0x7f020022;
        public static final int finishappsharp=0x7f020023;
        public static final int graycorners_button_bg=0x7f020024;
        public static final int group=0x7f020025;
        public static final int grzxbj=0x7f020026;
        public static final int hengtiao_hong=0x7f020027;
        public static final int home_btn_bg=0x7f020028;
        public static final int horizontal_preference_single_item=0x7f020029;
        public static final int hot=0x7f02002a;
        public static final int huibiaobeijing=0x7f02002b;
        public static final int ic_launcher=0x7f02002c;
        public static final int icon_more_nor=0x7f02002d;
        public static final int icon_more_sel=0x7f02002e;
        public static final int img_add=0x7f02002f;
        public static final int img_default=0x7f020030;
        public static final int img_loading=0x7f020031;
        public static final int info=0x7f020032;
        public static final int jiage=0x7f020033;
        public static final int jiazai_flase=0x7f020034;
        public static final int jingqgz=0x7f020035;
        public static final int list_item=0x7f020036;
        public static final int list_item_wangqi=0x7f020037;
        public static final int liwu=0x7f020038;
        public static final int login_check=0x7f020039;
        public static final int login_checked=0x7f02003a;
        public static final int login_pass=0x7f02003b;
        public static final int login_qq=0x7f02003c;
        public static final int login_user=0x7f02003d;
        public static final int login_weibo=0x7f02003e;
        public static final int login_weixin=0x7f02003f;
        public static final int logincodeleftsharp=0x7f020040;
        public static final int logincoderightsharp=0x7f020041;
        public static final int loginedt_shape=0x7f020042;
        public static final int logintxt_shape=0x7f020043;
        public static final int logo_qq=0x7f020044;
        public static final int logo_qzone=0x7f020045;
        public static final int logo_sinaweibo=0x7f020046;
        public static final int main_geren=0x7f020047;
        public static final int main_gerend=0x7f020048;
        public static final int main_gerened=0x7f020049;
        public static final int maintab_toolbar_bg=0x7f02004a;
        public static final int message=0x7f02004b;
        public static final int messagescenter_notice=0x7f02004c;
        public static final int mian_free=0x7f02004d;
        public static final int mian_freeed=0x7f02004e;
        public static final int mian_wangqi=0x7f02004f;
        public static final int mian_wangqied=0x7f020050;
        public static final int mianfeishiyong=0x7f020051;
        public static final int mianfsy=0x7f020052;
        public static final int morendizhi=0x7f020053;
        public static final int morendizhiweixuan=0x7f020054;
        public static final int my_bgxz=0x7f020055;
        public static final int my_imgpho=0x7f020056;
        public static final int my_imgphobg=0x7f020057;
        public static final int my_setting=0x7f020058;
        public static final int pencil=0x7f020059;
        public static final int pingfen=0x7f02005a;
        public static final int product=0x7f02005b;
        public static final int progressbar_mini=0x7f02005c;
        public static final int qibiao=0x7f02005d;
        public static final int qrdz=0x7f02005e;
        public static final int queding=0x7f02005f;
        public static final int radiosharp=0x7f020060;
        public static final int redandwithtext=0x7f020061;
        public static final int reload=0x7f020062;
        public static final int room_def_rating_bar=0x7f020063;
        public static final int room_def_select=0x7f020064;
        public static final int room_def_unselect=0x7f020065;
        public static final int room_rating_bar=0x7f020066;
        public static final int room_select=0x7f020067;
        public static final int room_unselect=0x7f020068;
        public static final int selecthot=0x7f020069;
        public static final int selector_maintab_background=0x7f02006a;
        public static final int selector_tab_background=0x7f02006b;
        public static final int selectordef_maintab_background=0x7f02006c;
        public static final int shanchu=0x7f02006d;
        public static final int share=0x7f02006e;
        public static final int shenhe=0x7f02006f;
        public static final int shiyongjieguo=0x7f020070;
        public static final int shiyongliucheng=0x7f020071;
        public static final int short_message_nor=0x7f020072;
        public static final int sns_qqfriends_icon=0x7f020073;
        public static final int sns_qzone_icon=0x7f020074;
        public static final int sns_sina_icon=0x7f020075;
        public static final int sns_weixin_icon=0x7f020076;
        public static final int sns_weixin_timeline_icon=0x7f020077;
        public static final int souce=0x7f020078;
        public static final int splark1=0x7f020079;
        public static final int splark2=0x7f02007a;
        public static final int splark3=0x7f02007b;
        public static final int ssdk_auth_title_back=0x7f02007c;
        public static final int ssdk_back_arr=0x7f02007d;
        public static final int ssdk_logo=0x7f02007e;
        public static final int ssdk_title_div=0x7f02007f;
        public static final int sureplace_che=0x7f020080;
        public static final int tab_home_btn=0x7f020081;
        public static final int tab_message_btn=0x7f020082;
        public static final int tab_more_btn=0x7f020083;
        public static final int tab_selfinfo_btn=0x7f020084;
        public static final int textcolorsharp=0x7f020085;
        public static final int tijiao=0x7f020086;
        public static final int tijiaoshiyongbaogao2=0x7f020087;
        public static final int tishi=0x7f020088;
        public static final int title_bg=0x7f020089;
        public static final int title_bg2=0x7f02008a;
        public static final int titlerelsharp=0x7f02008b;
        public static final int titletxtcolorsharp=0x7f02008c;
        public static final int topandbottomsharp=0x7f02008d;
        public static final int tpl_logo=0x7f02008e;
        public static final int tpl_title_back_arrow=0x7f02008f;
        public static final int tvbar=0x7f020090;
        public static final int tx=0x7f020091;
        public static final int waiguan=0x7f020092;
        public static final int waiguang=0x7f020093;
        public static final int wangqi_bi=0x7f020094;
        public static final int wangqi_gift=0x7f020095;
        public static final int weixuanzhong=0x7f020096;
        public static final int weizhongjiang=0x7f020097;
        public static final int wq_xq_01=0x7f020098;
        public static final int wq_xq_02=0x7f020099;
        public static final int wq_xq_03=0x7f02009a;
        public static final int wq_xq_04=0x7f02009b;
        public static final int write=0x7f02009c;
        public static final int xianjian01=0x7f02009d;
        public static final int xianjian02=0x7f02009e;
        public static final int xianjian04=0x7f02009f;
        public static final int xiaobiao=0x7f0200a0;
        public static final int xiaohongtiao=0x7f0200a1;
        public static final int xlistview_arrow=0x7f0200a2;
        public static final int yixuanzhong=0x7f0200a3;
        public static final int yonghu_moren=0x7f0200a4;
        public static final int youbiao_sanjiao=0x7f0200a5;
        public static final int youbiao_sanjiao_un=0x7f0200a6;
        public static final int zhaoxiangji=0x7f0200a7;
        public static final int zhaoxianji=0x7f0200a8;
        public static final int zhongjianglianjie=0x7f0200a9;
    }
    public static final class id {
        public static final int FILL=0x7f060001;
        public static final int ImageView01=0x7f060101;
        public static final int Qq=0x7f0600b9;
        public static final int Rl_change=0x7f06006a;
        public static final int STROKE=0x7f060000;
        public static final int Splash_viewpager=0x7f06006b;
        public static final int TextView01=0x7f0600d0;
        public static final int action_settings=0x7f06010b;
        public static final int add_edit=0x7f060017;
        /**  Messages IDs 
         */
        public static final int auto_focus=0x7f06000f;
        public static final int bigimage_wq=0x7f060078;
        public static final int botm=0x7f060019;
        public static final int bowlon=0x7f0600cb;
        public static final int btn_cancel=0x7f0600c1;
        public static final int btn_dialog_shouye=0x7f060081;
        public static final int btn_free_running=0x7f060050;
        public static final int btn_free_willdo=0x7f060051;
        public static final int btn_info_back=0x7f06004c;
        public static final int btn_send_pinglun=0x7f060090;
        public static final int btn_sureplace=0x7f0600f7;
        public static final int btn_sybaogao=0x7f0600ed;
        public static final int button1=0x7f060026;
        public static final int button1_=0x7f060066;
        /**  二维码 
         */
        public static final int decode=0x7f060008;
        public static final int decode_failed=0x7f060009;
        public static final int decode_succeeded=0x7f06000a;
        public static final int ed_by=0x7f0600f6;
        public static final int ed_sureplace_name=0x7f0600f1;
        public static final int ed_sureplace_phone=0x7f0600f3;
        public static final int ed_sureplace_place=0x7f0600f2;
        public static final int ed_sureplace_youbian=0x7f0600f4;
        public static final int ed_sybaogao_price=0x7f0600e7;
        public static final int ed_sybaogao_waiguan=0x7f0600e3;
        public static final int ed_sybaogao_xingneng=0x7f0600e5;
        public static final int ed_type=0x7f0600f5;
        public static final int edt_ads=0x7f060012;
        public static final int edt_code=0x7f060014;
        public static final int edt_email=0x7f06003b;
        public static final int edt_feed=0x7f060023;
        public static final int edt_nickname=0x7f06002c;
        public static final int edt_pass=0x7f060098;
        public static final int edt_pasw=0x7f0600b5;
        public static final int edt_phone=0x7f060013;
        public static final int edt_psw=0x7f060093;
        public static final int edt_pswd=0x7f060041;
        public static final int edt_putcode=0x7f060040;
        public static final int edt_rcode=0x7f06003d;
        public static final int edt_refcode=0x7f060095;
        public static final int edt_rpass=0x7f060099;
        public static final int edt_rpsw=0x7f060094;
        public static final int edt_rpswd=0x7f060042;
        public static final int edt_username=0x7f060011;
        public static final int et_write_pinglun=0x7f06008f;
        public static final int fx=0x7f0600c3;
        public static final int group_sex=0x7f060043;
        public static final int imageView1=0x7f060025;
        public static final int imageView2=0x7f0600d2;
        public static final int imageView3=0x7f0600d4;
        public static final int imageView4=0x7f0600d6;
        public static final int imageView5=0x7f0600d9;
        public static final int imageview=0x7f060097;
        public static final int img_back_01=0x7f060075;
        public static final int img_back_02=0x7f0600ef;
        public static final int img_back_03=0x7f0600db;
        public static final int img_back_04=0x7f0600f9;
        public static final int img_back_06=0x7f060048;
        public static final int img_back_product=0x7f060056;
        public static final int img_dialog_shouye=0x7f06007c;
        public static final int img_enter=0x7f06006e;
        public static final int img_exp=0x7f060083;
        public static final int img_left=0x7f0600ce;
        public static final int img_nononoway=0x7f0600e0;
        public static final int img_noway_bar=0x7f060052;
        public static final int img_noway_info_01=0x7f06004a;
        public static final int img_pro_info=0x7f06008d;
        public static final int img_product=0x7f0600a3;
        public static final int img_product_=0x7f06005b;
        public static final int img_share_02=0x7f060076;
        public static final int img_share_xiangqing=0x7f060058;
        public static final int img_show_item=0x7f0600d7;
        public static final int img_sybaogao=0x7f0600dc;
        public static final int img_sybaogao_camera=0x7f0600df;
        public static final int img_sybaogao_xieyi=0x7f0600ea;
        public static final int img_time=0x7f0600ad;
        public static final int img_time_=0x7f060067;
        public static final int img_tishi=0x7f06004d;
        public static final int img_title=0x7f0600aa;
        public static final int img_title_=0x7f060063;
        public static final int img_to_sy_pro=0x7f0600d1;
        public static final int img_tx=0x7f06009b;
        public static final int img_type=0x7f060085;
        public static final int img_user=0x7f0600b0;
        public static final int img_wangqi_user_l=0x7f0600fe;
        public static final int img_wangqi_user_r=0x7f060100;
        public static final int imgbtn_back=0x7f0600fc;
        public static final int imgbtn_sybg=0x7f0600cd;
        public static final int imgbtn_zjmd=0x7f0600cf;
        public static final int launch_product_query=0x7f06000b;
        public static final int layout_linear_free=0x7f06004f;
        public static final int layout_linear_l=0x7f060072;
        public static final int layout_linear_product=0x7f060071;
        public static final int layout_linear_r=0x7f060073;
        public static final int leftview=0x7f0600bc;
        public static final int lin_bot=0x7f0600b6;
        public static final int linear_imgs=0x7f06008c;
        public static final int linear_vp=0x7f0600c5;
        public static final int list_ads=0x7f060018;
        public static final int list_edit=0x7f060039;
        public static final int ll=0x7f06006c;
        public static final int login=0x7f06006d;
        public static final int login_check=0x7f060096;
        public static final int lv_main_run=0x7f060089;
        public static final int lv_main_will=0x7f06008b;
        public static final int lv_show_pinglun=0x7f060091;
        public static final int lv_wangqi_product=0x7f060077;
        public static final int lv_zjmd=0x7f0600fd;
        public static final int mProgress=0x7f0600ba;
        public static final int main=0x7f060027;
        public static final int main_radio=0x7f060002;
        public static final int msg=0x7f060020;
        public static final int my_aboutus=0x7f06009f;
        public static final int my_introd=0x7f06009e;
        public static final int my_setfeedbook=0x7f0600a0;
        public static final int my_setupdata=0x7f0600a1;
        public static final int nowei=0x7f06007f;
        public static final int pass=0x7f060087;
        public static final int pop_layout=0x7f0600bf;
        public static final int quit=0x7f06000c;
        public static final int radio_button0=0x7f060003;
        public static final int radio_button1=0x7f060004;
        public static final int radio_button2=0x7f060005;
        public static final int radio_button3=0x7f060006;
        public static final int radio_button4=0x7f060007;
        public static final int realtabcontent=0x7f060038;
        public static final int refrush_listview=0x7f060092;
        public static final int rel_recoaction=0x7f06009d;
        public static final int rela=0x7f06005a;
        public static final int restart_preview=0x7f06000d;
        public static final int return_scan_result=0x7f06000e;
        public static final int rl=0x7f06004e;
        public static final int rl01=0x7f060047;
        public static final int rl_1=0x7f0600ee;
        public static final int rl_2=0x7f0600da;
        public static final int rl_3=0x7f0600f8;
        public static final int rl_title=0x7f0600fb;
        public static final int rl_u_u=0x7f060055;
        public static final int rpass=0x7f060088;
        public static final int scroll_extend=0x7f060059;
        public static final int set_ads=0x7f060032;
        public static final int set_email=0x7f06002e;
        public static final int set_img=0x7f06002a;
        public static final int set_moblie=0x7f06002d;
        public static final int set_psw=0x7f060034;
        public static final int set_sex=0x7f060030;
        public static final int set_username=0x7f06002b;
        public static final int sex_man=0x7f060044;
        public static final int sex_none=0x7f060046;
        public static final int sex_woman=0x7f060045;
        public static final int share=0x7f060028;
        public static final int share_gridview=0x7f0600c0;
        public static final int share_icon=0x7f0600bd;
        public static final int share_parent=0x7f060054;
        public static final int share_title=0x7f0600be;
        public static final int share_wangqi=0x7f060074;
        public static final int star_sybaogao=0x7f0600e9;
        public static final int star_zonghe=0x7f0600d8;
        public static final int submit=0x7f060024;
        public static final int suiyiyiyi=0x7f060080;
        public static final int sv_wqhg=0x7f060070;
        public static final int textView1=0x7f06007e;
        public static final int textView2=0x7f0600fa;
        public static final int textview=0x7f0600bb;
        public static final int timer_text_view=0x7f0600ae;
        public static final int timer_text_view_=0x7f060068;
        public static final int top=0x7f060015;
        public static final int tvWeibo=0x7f0600b8;
        public static final int tvWeixin=0x7f0600b7;
        public static final int tv_dialog_shouye=0x7f06007d;
        public static final int tv_free01=0x7f0600a4;
        public static final int tv_free01_=0x7f06005c;
        public static final int tv_free02=0x7f0600a7;
        public static final int tv_free02_=0x7f06005f;
        public static final int tv_info_pinglun=0x7f06008e;
        public static final int tv_no=0x7f0600a9;
        public static final int tv_no_=0x7f060061;
        public static final int tv_nono=0x7f0600a6;
        public static final int tv_nono_=0x7f06005e;
        public static final int tv_noway_=0x7f0600eb;
        public static final int tv_noway_info_02=0x7f060049;
        public static final int tv_noway_info_04=0x7f06004b;
        public static final int tv_num=0x7f0600a5;
        public static final int tv_num_=0x7f06005d;
        public static final int tv_persons=0x7f0600a8;
        public static final int tv_persons_=0x7f060060;
        public static final int tv_pinglu=0x7f0600b2;
        public static final int tv_price=0x7f060062;
        public static final int tv_product_content=0x7f0600ab;
        public static final int tv_product_content_=0x7f060064;
        public static final int tv_product_title=0x7f0600ac;
        public static final int tv_product_title_=0x7f060065;
        public static final int tv_qi_num=0x7f0600af;
        public static final int tv_qi_num_=0x7f060069;
        public static final int tv_sureplace_info=0x7f0600f0;
        public static final int tv_sybaogao_info=0x7f0600de;
        public static final int tv_sybaogao_pingfen=0x7f0600e8;
        public static final int tv_sybaogao_price=0x7f0600e6;
        public static final int tv_sybaogao_tishi=0x7f0600e1;
        public static final int tv_sybaogao_title=0x7f0600dd;
        public static final int tv_sybaogao_waiguan=0x7f0600e2;
        public static final int tv_sybaogao_xieyi=0x7f0600ec;
        public static final int tv_sybaogao_xingneng=0x7f0600e4;
        public static final int tv_time=0x7f0600b3;
        public static final int tv_title_bar_free=0x7f0600c2;
        public static final int tv_username=0x7f0600b1;
        public static final int tv_waiguan=0x7f0600d3;
        public static final int tv_wangqi_baogaotijiao=0x7f0600cc;
        public static final int tv_wangqi_listitem1_scores=0x7f0600c7;
        public static final int tv_wangqi_listitem1_some=0x7f0600c8;
        public static final int tv_wangqi_listitem1_title=0x7f0600c6;
        public static final int tv_wangqi_sureplace=0x7f0600ca;
        public static final int tv_wangqi_username_l=0x7f0600ff;
        public static final int tv_wangqi_username_r=0x7f060102;
        public static final int tv_wqhg_title=0x7f06006f;
        public static final int tv_xiangqing_title=0x7f060057;
        public static final int tv_zhiliang=0x7f0600d5;
        public static final int txt_ads=0x7f06001e;
        public static final int txt_album=0x7f060079;
        public static final int txt_backg=0x7f060029;
        public static final int txt_bowl=0x7f0600b4;
        public static final int txt_code=0x7f06003e;
        public static final int txt_def=0x7f06001d;
        public static final int txt_delect=0x7f06001b;
        public static final int txt_edit=0x7f06001a;
        public static final int txt_email=0x7f06002f;
        public static final int txt_enter=0x7f060022;
        public static final int txt_exit=0x7f060021;
        public static final int txt_fidtxt=0x7f06003f;
        public static final int txt_finish=0x7f060036;
        public static final int txt_going=0x7f06008a;
        public static final int txt_left=0x7f060033;
        public static final int txt_mobile=0x7f06001f;
        public static final int txt_myset=0x7f06009a;
        public static final int txt_nickname=0x7f06009c;
        public static final int txt_period=0x7f060082;
        public static final int txt_photo=0x7f06007a;
        public static final int txt_price=0x7f0600c9;
        public static final int txt_psw=0x7f060035;
        public static final int txt_rdt=0x7f060016;
        public static final int txt_sex=0x7f060031;
        public static final int txt_time=0x7f060084;
        public static final int txt_title=0x7f060037;
        public static final int txt_top=0x7f06003a;
        public static final int txt_type=0x7f060086;
        public static final int txt_upmsg=0x7f0600a2;
        public static final int txt_username=0x7f06001c;
        public static final int txt_verif=0x7f06003c;
        public static final int vp=0x7f0600c4;
        public static final int vp_product_list=0x7f060053;
        public static final int wb_agment=0x7f060010;
        public static final int xlistview_footer_content=0x7f060103;
        public static final int xlistview_footer_hint_textview=0x7f060105;
        public static final int xlistview_footer_progressbar=0x7f060104;
        public static final int xlistview_header_arrow=0x7f06010a;
        public static final int xlistview_header_content=0x7f060106;
        public static final int xlistview_header_hint_textview=0x7f060108;
        public static final int xlistview_header_progressbar=0x7f06007b;
        public static final int xlistview_header_text=0x7f060107;
        public static final int xlistview_header_time=0x7f060109;
    }
    public static final class integer {
        /**  shareSDK三方登录 
         */
        public static final int app_version_code=0x7f0a0000;
    }
    public static final class layout {
        public static final int activity_aboutus=0x7f030000;
        public static final int activity_addads=0x7f030001;
        public static final int activity_ads=0x7f030002;
        public static final int activity_adsit=0x7f030003;
        public static final int activity_diapros=0x7f030004;
        public static final int activity_feedbook=0x7f030005;
        public static final int activity_introd=0x7f030006;
        public static final int activity_load_false=0x7f030007;
        public static final int activity_main=0x7f030008;
        public static final int activity_perset=0x7f030009;
        public static final int activity_register=0x7f03000a;
        public static final int activity_setads=0x7f03000b;
        public static final int activity_setemail=0x7f03000c;
        public static final int activity_setmobile=0x7f03000d;
        public static final int activity_setpsw=0x7f03000e;
        public static final int activity_setpswemail=0x7f03000f;
        public static final int activity_setpswnext=0x7f030010;
        public static final int activity_setsex=0x7f030011;
        public static final int activity_shouye_appleytry_false=0x7f030012;
        public static final int activity_shouye_dialog_info=0x7f030013;
        public static final int activity_shouye_main=0x7f030014;
        public static final int activity_shouye_product=0x7f030015;
        public static final int activity_splash=0x7f030016;
        public static final int activity_succpsw=0x7f030017;
        public static final int activity_wangqi_main=0x7f030018;
        public static final int activity_wangqi_product=0x7f030019;
        public static final int activity_win=0x7f03001a;
        public static final int agreemactivity=0x7f03001b;
        public static final int bigimage_wangqi=0x7f03001c;
        public static final int botmselectlayout=0x7f03001d;
        public static final int common_flipping_loading_diloag=0x7f03001e;
        public static final int dialog_shouye=0x7f03001f;
        public static final int explist_child=0x7f030020;
        public static final int explist_title=0x7f030021;
        public static final int fragment_findemil=0x7f030022;
        public static final int fragment_findphone=0x7f030023;
        public static final int fragment_shouye_main_run=0x7f030024;
        public static final int fragment_shouye_main_will=0x7f030025;
        public static final int fragment_shouye_product_info=0x7f030026;
        public static final int fragment_shouye_product_pinglun=0x7f030027;
        public static final int fragmentmailbox=0x7f030028;
        public static final int fragmentold=0x7f030029;
        public static final int fragmentphone=0x7f03002a;
        public static final int fragmenttrial=0x7f03002b;
        public static final int fragmnetmy=0x7f03002c;
        public static final int imageview_layout=0x7f03002d;
        public static final int list_shouye_main_item=0x7f03002e;
        public static final int list_shouye_pinglun_item=0x7f03002f;
        public static final int login=0x7f030030;
        public static final int main_tab_layout=0x7f030031;
        public static final int progress=0x7f030032;
        public static final int recoadapter_item=0x7f030033;
        public static final int rettab_item_view=0x7f030034;
        public static final int rettabdef_item_view=0x7f030035;
        public static final int share_item=0x7f030036;
        public static final int share_layout=0x7f030037;
        public static final int tab_item_view=0x7f030038;
        public static final int title_bar_free=0x7f030039;
        public static final int tpl_login_page=0x7f03003a;
        public static final int tpl_progress_dialog=0x7f03003b;
        public static final int wangqi_product_item_0=0x7f03003c;
        public static final int wangqi_product_item_1=0x7f03003d;
        public static final int wangqi_product_item_2=0x7f03003e;
        public static final int wangqi_shiyongbaogao=0x7f03003f;
        public static final int wangqi_sureplace=0x7f030040;
        public static final int wangqi_tijiaoganxie=0x7f030041;
        public static final int wangqi_zhongjiangmingdan=0x7f030042;
        public static final int wangqi_zjmd_item=0x7f030043;
        public static final int xlistview_footer=0x7f030044;
        public static final int xlistview_header=0x7f030045;
    }
    public static final class menu {
        public static final int main=0x7f0c0000;
    }
    public static final class raw {
        public static final int baidu_beep=0x7f050000;
        public static final int beep=0x7f050001;
        public static final int weixin_beep=0x7f050002;
    }
    public static final class string {
        public static final int aboutncwc=0x7f09005a;
        public static final int aboutsmsg=0x7f09005d;
        public static final int aboutsus=0x7f090099;
        public static final int aboutus=0x7f090059;
        public static final int action_settings=0x7f090032;
        public static final int actionint=0x7f090058;
        public static final int actionrec=0x7f090057;
        public static final int add_ads=0x7f090083;
        public static final int add_code=0x7f090085;
        public static final int add_moblie=0x7f090084;
        public static final int add_msg=0x7f090081;
        public static final int add_name=0x7f090082;
        /**  地址管理 
         */
        public static final int addads=0x7f09007f;
        public static final int adsmanagement=0x7f09006d;
        public static final int after_auth=0x7f0900b6;
        public static final int agreement=0x7f0900a0;
        public static final int agreemented=0x7f0900a1;
        public static final int app_name=0x7f090031;
        public static final int app_version=0x7f0900a9;
        public static final int auth_cancel=0x7f0900b2;
        public static final int auth_complete=0x7f0900b4;
        public static final int auth_error=0x7f0900b3;
        public static final int automatic=0x7f09004e;
        public static final int back=0x7f09009e;
        public static final int beillemail=0x7f09008c;
        public static final int beillphone=0x7f09008b;
        public static final int bindphone=0x7f090071;
        public static final int binemail=0x7f090075;
        /**  免费试用 
         */
        public static final int bouttobegin=0x7f09003d;
        public static final int cancel=0x7f0900a7;
        public static final int delect=0x7f0900a3;
        public static final int douban=0x7f09001a;
        public static final int dropbox=0x7f090024;
        public static final int edit=0x7f0900a2;
        public static final int editads=0x7f090080;
        public static final int email=0x7f090015;
        public static final int emailsucced=0x7f09008a;
        /**  通用 
         */
        public static final int enter=0x7f09009d;
        public static final int enteremilpsw=0x7f090054;
        public static final int enterphonepsw=0x7f090053;
        public static final int evernote=0x7f09001c;
        public static final int exampleads=0x7f09007a;
        public static final int exampleeamil=0x7f09007b;
        public static final int examplemsg=0x7f09005b;
        public static final int examplesex=0x7f09007c;
        public static final int exampletime=0x7f09005c;
        public static final int facebook=0x7f090011;
        public static final int fedpas=0x7f090052;
        public static final int feedback=0x7f09005e;
        public static final int feedbookmsg=0x7f09009a;
        public static final int fidpsw=0x7f09004b;
        public static final int finishapp=0x7f09006e;
        public static final int finishappenter=0x7f09006f;
        public static final int flickr=0x7f090022;
        public static final int foursquare=0x7f09001f;
        /**  活动介绍 
         */
        public static final int freeproces=0x7f09008e;
        public static final int freequalif=0x7f090097;
        public static final int freeresturn=0x7f090094;
        public static final int freesubmit=0x7f090095;
        public static final int fromalbumselection=0x7f09007d;
        public static final int google_plus_client_inavailable=0x7f090005;
        public static final int googleplus=0x7f09001e;
        public static final int grade=0x7f090060;
        public static final int if_register_needed=0x7f0900b5;
        public static final int immdownload=0x7f09009c;
        public static final int infinish=0x7f0900a6;
        public static final int instagram=0x7f090026;
        public static final int instagram_client_inavailable=0x7f090008;
        public static final int instapager_login_html=0x7f090000;
        public static final int integral=0x7f090061;
        public static final int kaixin=0x7f090014;
        public static final int line=0x7f09002a;
        public static final int line_client_inavailable=0x7f09000a;
        public static final int linkedin=0x7f09001d;
        /**  登录 注册 
         */
        public static final int login=0x7f090045;
        public static final int login_with_other_plat=0x7f0900af;
        public static final int login_with_qq=0x7f0900ae;
        public static final int login_with_sina_weibo=0x7f0900ad;
        public static final int login_with_weixin=0x7f0900ac;
        public static final int logining=0x7f0900b1;
        public static final int mingdao=0x7f090029;
        public static final int mingdao_share_content=0x7f09002d;
        public static final int mobli=0x7f090066;
        public static final int modifemail=0x7f090076;
        public static final int modifnickname=0x7f090078;
        public static final int modifnsex=0x7f090079;
        public static final int modifymoile=0x7f090072;
        public static final int modpsw=0x7f090070;
        public static final int name=0x7f090046;
        public static final int neteasemicroblog=0x7f090019;
        public static final int new_name=0x7f090087;
        /**  密码服务 
         */
        public static final int new_pswd=0x7f090086;
        public static final int next=0x7f09009f;
        public static final int nickname=0x7f090063;
        public static final int noselect=0x7f090041;
        public static final int pass=0x7f090047;
        public static final int percenter=0x7f090056;
        /**  个人中心 
         */
        public static final int persettion=0x7f090055;
        public static final int phonesucced=0x7f090089;
        public static final int photograph=0x7f09007e;
        public static final int pinterest=0x7f090021;
        public static final int pinterest_client_inavailable=0x7f090007;
        public static final int product_info=0x7f09003f;
        public static final int proj_name=0x7f0900aa;
        public static final int psw=0x7f090048;
        public static final int putemail=0x7f090051;
        public static final int putnick=0x7f090067;
        public static final int putnickname=0x7f090050;
        public static final int pwdservice=0x7f09006c;
        public static final int qq=0x7f090020;
        public static final int qq_client_inavailable=0x7f090006;
        public static final int qzone=0x7f09000d;
        public static final int refcode=0x7f09004a;
        public static final int reig=0x7f09004d;
        public static final int rember=0x7f09004f;
        public static final int removeeamil=0x7f090077;
        public static final int removeemail=0x7f09008d;
        public static final int removemoile=0x7f090073;
        public static final int renren=0x7f090013;
        public static final int resetpsw=0x7f09004c;
        public static final int rpass=0x7f090049;
        public static final int selectdefult=0x7f090065;
        public static final int setdefult=0x7f090064;
        public static final int setsex=0x7f090074;
        public static final int sex=0x7f090068;
        public static final int sex_man=0x7f090069;
        public static final int sex_none=0x7f09006b;
        public static final int sex_woman=0x7f09006a;
        public static final int share_sdk=0x7f0900ab;
        public static final int share_to_mingdao=0x7f09002e;
        public static final int share_to_qq=0x7f09002c;
        public static final int share_to_qzone=0x7f09002b;
        public static final int share_to_qzone_default=0x7f09002f;
        public static final int shiyongbaogao=0x7f090042;
        public static final int shortmessage=0x7f090016;
        public static final int signup_failed=0x7f0900ce;
        public static final int signup_success=0x7f0900cd;
        public static final int sinaweibo=0x7f09000b;
        public static final int sohumicroblog=0x7f090017;
        public static final int sohusuishenkan=0x7f090018;
        public static final int souces=0x7f09008f;
        public static final int souces1=0x7f090090;
        public static final int souces2=0x7f090091;
        public static final int souces3=0x7f090092;
        public static final int souces4=0x7f090093;
        public static final int submit=0x7f0900a5;
        public static final int succed=0x7f090088;
        /**  往期回顾 
         */
        public static final int suresplace=0x7f090040;
        /**  主界面 
         */
        public static final int tab_function=0x7f09003a;
        public static final int tab_self=0x7f09003c;
        public static final int tab_shopping=0x7f09003b;
        public static final int tencentweibo=0x7f09000c;
        public static final int tijiaosybg=0x7f090043;
        public static final int tip=0x7f0900a4;
        public static final int tip_content=0x7f0900a8;
        public static final int tpl_boy=0x7f0900c1;
        public static final int tpl_camera=0x7f0900c2;
        public static final int tpl_cancel=0x7f0900b8;
        public static final int tpl_change_user_name_title=0x7f0900c4;
        public static final int tpl_change_user_note_title=0x7f0900c5;
        public static final int tpl_get_verify_code=0x7f0900cb;
        public static final int tpl_girl=0x7f0900c0;
        public static final int tpl_input_user_name_hint=0x7f0900c6;
        public static final int tpl_input_user_note_hint=0x7f0900c7;
        public static final int tpl_key_user_gender=0x7f0900bb;
        public static final int tpl_key_user_icon=0x7f0900b9;
        public static final int tpl_key_user_name=0x7f0900ba;
        public static final int tpl_key_user_note=0x7f0900bc;
        public static final int tpl_msg_login_hint=0x7f0900c9;
        public static final int tpl_no_sdcard=0x7f0900c8;
        public static final int tpl_ok=0x7f0900b7;
        public static final int tpl_picture=0x7f0900c3;
        public static final int tpl_send_verify_code=0x7f0900cc;
        public static final int tpl_sign_up=0x7f0900bf;
        public static final int tpl_sign_user_info=0x7f0900be;
        public static final int tpl_value_user_note=0x7f0900bd;
        public static final int tpl_verify_code_hint=0x7f0900ca;
        public static final int trialresults=0x7f090098;
        public static final int trila=0x7f09003e;
        public static final int tumblr=0x7f090023;
        public static final int twitter=0x7f090012;
        /**  下载更新 
         */
        public static final int upmsg=0x7f09009b;
        public static final int use_login_button=0x7f090030;
        public static final int userid_found=0x7f0900b0;
        /**  个人设置 
         */
        public static final int username=0x7f090062;
        public static final int usprocess=0x7f090096;
        public static final int versionup=0x7f09005f;
        public static final int vkontakte=0x7f090025;
        public static final int website=0x7f090002;
        public static final int wechat=0x7f09000e;
        public static final int wechat_client_inavailable=0x7f090004;
        public static final int wechatfavorite=0x7f090010;
        public static final int wechatmoments=0x7f09000f;
        public static final int weibo_oauth_regiseter=0x7f090001;
        public static final int weibo_upload_content=0x7f090003;
        public static final int xlistview_footer_hint_normal=0x7f090038;
        public static final int xlistview_footer_hint_ready=0x7f090039;
        public static final int xlistview_header_hint_loading=0x7f090036;
        /**  刷新 
         */
        public static final int xlistview_header_hint_normal=0x7f090033;
        public static final int xlistview_header_hint_ready=0x7f090034;
        public static final int xlistview_header_hintbm=0x7f090035;
        public static final int xlistview_header_last_time=0x7f090037;
        public static final int yixin=0x7f090027;
        public static final int yixin_client_inavailable=0x7f090009;
        public static final int yixinmoments=0x7f090028;
        public static final int youdao=0x7f09001b;
        public static final int zhongjiangMD=0x7f090044;
    }
    public static final class style {
        public static final int AnimBottom=0x7f0b0005;
        public static final int AnimationActivity=0x7f0b0006;
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.







    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
            36*36    -l
			48*48    -m
			72*72    -h
			96*96   -xh







        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f0b0000;
        /**  确认按钮样式 
         */
        public static final int Btn_entenrTheme=0x7f0b0015;
        /**  dialog 
         */
        public static final int CommonDialog=0x7f0b0001;
        public static final int CustomCheckboxTheme=0x7f0b0011;
        public static final int CustomCheckboxTheme2=0x7f0b0012;
        /**  ShouYeInfoProduct.... 
         */
        public static final int CustomDialogStyle=0x7f0b001f;
        /**  输入框样式 
         */
        public static final int EdittextTheme=0x7f0b0014;
        public static final int LeftAndRightThem=0x7f0b0013;
        /**  对话框样式 
         */
        public static final int MyDialogStyle=0x7f0b0016;
        /**  模糊 
         */
        public static final int MyDialogStyleBottom=0x7f0b0008;
        public static final int PopupAnimation=0x7f0b0003;
        /**  进度条样式 
         */
        public static final int ProgressBar_Mini=0x7f0b0009;
        public static final int ThemeActivity=0x7f0b0007;
        /**  white dialog 
         */
        public static final int WhiteDialog=0x7f0b0002;
        /**  基础textview样式 
         */
        public static final int base_thetextView=0x7f0b000b;
        public static final int horizontal_preference_single_item=0x7f0b0017;
        public static final int main_tab_bottom=0x7f0b0004;
        public static final int myset_centext=0x7f0b0019;
        public static final int myset_leftimgitem=0x7f0b0018;
        public static final int myset_rightimgitem=0x7f0b001c;
        /**  最外层activity样式 
         */
        public static final int parentcontainer=0x7f0b0010;
        public static final int relativeLayout_item_lineView=0x7f0b000f;
        public static final int relativeLayout_title=0x7f0b000a;
        public static final int relativeLayout_title_leftTextView=0x7f0b000d;
        public static final int relativeLayout_title_rightTextView=0x7f0b000e;
        public static final int relativeLayout_title_textView=0x7f0b000c;
        /**  RatingBar样式 
         */
        public static final int roomRatingBar=0x7f0b001d;
        public static final int roomRatingBar_defuel=0x7f0b001e;
        public static final int set_context=0x7f0b001a;
        public static final int set_contextright=0x7f0b001b;
    }
    public static final class styleable {
        /** Attributes that can be used with a RoundProgressBar.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RoundProgressBar_max com.ncwcandroid.ui:max}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundColor com.ncwcandroid.ui:roundColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundProgressColor com.ncwcandroid.ui:roundProgressColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundWidth com.ncwcandroid.ui:roundWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_style com.ncwcandroid.ui:style}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textColor com.ncwcandroid.ui:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textIsDisplayable com.ncwcandroid.ui:textIsDisplayable}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textSize com.ncwcandroid.ui:textSize}</code></td><td></td></tr>
           </table>
           @see #RoundProgressBar_max
           @see #RoundProgressBar_roundColor
           @see #RoundProgressBar_roundProgressColor
           @see #RoundProgressBar_roundWidth
           @see #RoundProgressBar_style
           @see #RoundProgressBar_textColor
           @see #RoundProgressBar_textIsDisplayable
           @see #RoundProgressBar_textSize
         */
        public static final int[] RoundProgressBar = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#max}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:max
        */
        public static final int RoundProgressBar_max = 5;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#roundColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:roundColor
        */
        public static final int RoundProgressBar_roundColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#roundProgressColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:roundProgressColor
        */
        public static final int RoundProgressBar_roundProgressColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#roundWidth}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:roundWidth
        */
        public static final int RoundProgressBar_roundWidth = 2;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#style}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>STROKE</code></td><td>0</td><td></td></tr>
<tr><td><code>FILL</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.ncwcandroid.ui:style
        */
        public static final int RoundProgressBar_style = 7;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#textColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:textColor
        */
        public static final int RoundProgressBar_textColor = 3;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#textIsDisplayable}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:textIsDisplayable
        */
        public static final int RoundProgressBar_textIsDisplayable = 6;
        /**
          <p>This symbol is the offset where the {@link com.ncwcandroid.ui.R.attr#textSize}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ncwcandroid.ui:textSize
        */
        public static final int RoundProgressBar_textSize = 4;
    };
}
